name: Format and Push with Biome

on:
  push:
    branches:
      - develop

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia la versión de Node.js si es necesario

      - name: Run Biome formatter
        run: |
          npx biome format .  # Ejecuta el formateo en todo el repositorio usando npx

      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "::set-output name=changes::changes"

      - name: Commit and push changes
        if: steps.git_diff.outputs.changes == 'changes'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Apply Biome formatting"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
