name: Detectar Consola con Node.js

on: [push, pull_request]

jobs:
 detect-console:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Detectar Consola
      run: |
        node -e "if (typeof console !== 'undefined') { console.log('La consola está disponible.'); } else { console.log('La consola no está disponible.'); }"
