name: Deploy
on:
 pull_request:
    types:
      - opened

jobs:
 build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: appleboy/run-command-action@master
        with:
          command: |
            find . -type f -exec sed -i 's/console\.log\(([^)]*)\);//g' {} +
      
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Remove console.log statements"
       
