name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Script de bash para buscar y eliminar las llamadas a console.log en varios tipos de archivos
      - name: Remove console.log statements
        run: |
          find . -type f \( -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx" \) -exec sed -i '/console\.log/d' {} +
