name: Deploy
on:
 pull_request:
    types:
      - opened

jobs:
 build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "hello"
          replace: ""
          regex: true
        env:
          DEBUG: 'true'
      
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Remove console.log statements"
       
