name: My Workflow
on: [push, pull_request]
jobs:
 build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "console\\.log\\(([^)]+)\\)"
          replace: ""
          regex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Remove console.log statements"
